/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-2',
    aws_cognito_identity_pool_id: 'us-east-2:c0d36eee-6a2b-4e96-a7e8-eb5fd8c34f00',
    aws_cognito_region: 'us-east-2',
    aws_user_pools_id: 'us-east-2_QzkMkVq5N',
    aws_user_pools_web_client_id: '39t138pv21dkhl5m540ms4jjol',
    oauth: {
        domain: 'playground-dev.auth.us-east-2.amazoncognito.com',
        scope: ['email', 'openid', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'https://master.d2op2qjtcv1lql.amplifyapp.com/',
        redirectSignOut: 'https://master.d2op2qjtcv1lql.amplifyapp.com/',
        responseType: 'code'
    },
    federationTarget: 'COGNITO_USER_POOLS'
};

export default awsmobile;
